// Auto-generated from DISC.xlsm. Do not edit manually.

export const DISC_COMBINATIONS: Record<string, string> = {
  "Código": "Concatenado",
  "123": "A combinação de 3 perfis Dominantes é algo raro de acontecer, isso é uma coisa boa, pois você terá o melhor de cada mundo a seu dispor, em contrapartida, você também terá características conflitantes de perfis antagônicos, como é o caso do D (Dominância) e S (Estabilidade). Ao mesmo tempo em que o D (Dominância) tende a realizar as atividades, o S (Estabilidade) tende a avaliar todos os caminhos possíveis, porém pelo fato de haver o I (Influente) também presente em seu perfil, a tendência é que as características do perfil D (Dominância) se sobressaiam, pois tanto o D quanto o I são imediatistas e tendem a resolver as coisas o quanto antes. \nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "124": "A combinação de 3 perfis Dominantes é algo raro de acontecer, isso é uma coisa boa, pois você terá o melhor de cada mundo a seu dispor, em contrapartida, você também terá características conflitantes de perfis antagônicos, no caso dessa combinação, o conflito ocorre entre perfis com uma boa comunicação e um alto grau de extroversão, D (Dominância) e I (Influência)), com o perfil C (Conformidade) que é um perfil mais reservado. Com a clareza da situação, é possível aproveitar a sinergia, empolgação e iniciativa da combinação Dominância/Influência para aproveitar o que há de melhor na análise precisa gerada pelo alto C (Conformidade) das situações.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "132": "A combinação de 3 perfis Dominantes é algo raro de acontecer, isso é uma coisa boa, pois você terá o melhor de cada mundo a seu dispor, em contrapartida, você também terá características conflitantes de perfis antagônicos,  o que não necessariamente é o caso dessa combinação. Pessoas com essa combinação possuem características que combinam entre si, então a possibilidade de conflitos é menor. Há é claro a ressalva entre a iniciativa do alto D (Dominância) maior perfil nesse caso e do alto S (Estabilidade). Nessa situação a dificuldade ocorre pela necessidade do D (Dominância) realizar as atividades, conflitar com a necessidade de avaliação e criação de um plano de ação do perfil S (Estabilidade), porém, havendo o equilíbrio entre ambos, ocorre o melhor de dois mundos.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "134": "A combinação de 3 perfis Dominantes é algo raro de acontecer, isso é uma coisa boa, pois você terá o melhor de cada mundo a seu dispor, em contrapartida, você também terá características conflitantes de perfis antagônicos,  nessa combinação, a dificuldade ocorre pela necessidade do D (Dominância) realizar as atividades, conflitar com a necessidade de avaliação e criação de um plano de ação gerada pelo S (Estabilidade) e muito bem analisado com as características de seu C (Conformidade), porém, havendo o equilíbrio entre ambos, ocorre o melhor de dois mundos, com a criação de um plano de ação ágil e uma execução impecável.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "142": "A combinação de 3 perfis Dominantes é algo raro de acontecer, isso é uma coisa boa, pois você terá o melhor de cada mundo a seu dispor, em contrapartida, você também terá características conflitantes de perfis antagônicos, no caso dessa combinação, o conflito ocorre entre perfis com uma boa comunicação e um alto grau de extroversão, D (Dominância) e I (Influência), com o perfil C (Conformidade) que é um perfil mais reservado, que antes de tomar qualquer atitude avalia todos os pontos. Com a clareza da situação, é possível aproveitar a sinergia, empolgação e iniciativa da combinação Dominância/Influência para aproveitar o que há de melhor na análise precisa gerada pelo alto C (Conformidade) das situações.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "143": "A combinação de 3 perfis Dominantes é algo raro de acontecer, isso é uma coisa boa, pois você terá o melhor de cada mundo a seu dispor, em contrapartida, você também terá características conflitantes de perfis antagônicos, nessa combinação, existem 2 perfis que tendem a planejar, analisar as informações antes de agir, o C (Conformidade) e o S (Estabilidade), mas a depender de como o maior perfil dominante, o D (Dominância), está, as características são apagadas, já que o D tende a apenas realizar atividades. Com a clareza das características de cada um e a combinação dos melhores pontos, a possibilidade de qualquer plano dar certo é incrível.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "213": "A combinação de 3 perfis Dominantes é algo raro de acontecer, isso é uma coisa boa, pois você terá o melhor de cada mundo a seu dispor, em contrapartida, você também terá características conflitantes de perfis antagônicos, a combinação de I (Influência) e D (Dominância) é super vantajosa para essa pessoa, pois a facilidade da comunicação com a eficácia da execução trás um resultado certo, alinhando isso ao terceiro perfil dominante desse perfil, o S (Estabilidade), as coisas ficam incríveis. O ponto de atenção ocorre com o conflito que pode ocorrer entre seu lado Influente e Conforme, mas sabendo que ambos existem, gerar uma coexistência focada no ganho é o melhor caminho.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "214": "A combinação de 3 perfis Dominantes é algo raro de acontecer, isso é uma coisa boa, pois você terá o melhor de cada mundo a seu dispor, em contrapartida, você também terá características conflitantes de perfis antagônicos, no caso dessa combinação, o conflito ocorre entre perfis com uma boa comunicação e um alto grau de extroversão, D (Dominância) e I (Influência), com o perfil C (Conformidade) que é um perfil mais reservado. Com a clareza da situação, é possível aproveitar a sinergia, empolgação e iniciativa da combinação Dominância/Influência para aproveitar o que há de melhor na análise precisa gerada pelo alto C (Conformidade) das situações.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "231": "A combinação de 3 perfis Dominantes é algo raro de acontecer, isso é uma coisa boa, pois você terá o melhor de cada mundo a seu dispor, em contrapartida, você também terá características conflitantes de perfis antagônicos, nessa trinca de perfis, o I (Influência) tende a assumir as rédeas da situação sendo ajudado pelo D (Dominância), pois possuem algumas características semelhantes, porém ao se deparar com o S (Estabilidade), pode ocorrer certa frustração ao não planejar ou mesmo ao planejar, por isso é preciso usar as melhores características de cada perfil a seu favor no dia a dia.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "234": "A combinação de 3 perfis Dominantes é algo raro de acontecer, isso é uma coisa boa, pois você terá o melhor de cada mundo a seu dispor, em contrapartida, você também terá características conflitantes de perfis antagônicos, na combinação desse perfil, I (Influência) / S (Estabilidade) / C (Conformidade) podem ocorrer \"faíscas\" internas ao precisar tomar algumas decisões, isso ocorre pois seu lado Conforme que avaliar as informações possibilitando ao Estável traçar o melhor plano, porém um Influente dominante não aceita ser deixado de lado e se entedia fácil, por isso o foco pode ser afetado para quem possui essa tríade.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "241": "A combinação de 3 perfis Dominantes é algo raro de acontecer, isso é uma coisa boa, pois você terá o melhor de cada mundo a seu dispor, em contrapartida, você também terá características conflitantes de perfis antagônicos, no caso dessa combinação, o conflito ocorre entre perfis com uma boa comunicação e um alto grau de extroversão, D (Dominância) e I (Influência), com o perfil C (Conformidade) que é um perfil mais reservado e que antes de tomar qualquer atitude avalia todos os pontos. Com a clareza da situação, é possível aproveitar a sinergia, empolgação e iniciativa da combinação Dominância/Influência para aproveitar o que há de melhor na análise precisa gerada pelo alto C (Conformidade) das situações.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "243": "A combinação de 3 perfis Dominantes é algo raro de acontecer, isso é uma coisa boa, pois você terá o melhor de cada mundo a seu dispor, em contrapartida, você também terá características conflitantes de perfis antagônicos, essa tríade causa grande desconforto em alguns momentos, pois o maior perfil é o I (Influência) que não lida bem com processos, rotinas, análises e planos, porém os demais perfis dessa combinação trabalham muito bem nesse cenário, logo, havendo o devido equilíbrio vindo da clareza de como cada perfil influencia na sua vida, você poderá aproveitar o melhor de cada mundo.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "312": "A combinação de 3 perfis Dominantes é algo raro de acontecer, isso é uma coisa boa, pois você terá o melhor de cada mundo a seu dispor, em contrapartida, você também terá características conflitantes de perfis antagônicos, como é o caso do D (Dominância) e S (Estabilidade). Ao mesmo tempo em que o Dominante tende a realizar as atividades, o Estável tende a avaliar todos os caminhos possíveis. Sendo a maior dominância do Estável, a tendência é não sair fazendo, porém com a junção do perfil I (Influência) a impulsividade vem a tona e é preciso tomar cuidado para não se entediar ao criar um plano e sair executando sem avaliar adequadamente. A combinação desses perfis possibilita grandes conquistas, mas apenas se for tratada adequadamente, o que virá da clareza que você terá a partir de agora. \nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "314": "A combinação de 3 perfis Dominantes é algo raro de acontecer, isso é uma coisa boa, pois você terá o melhor de cada mundo a seu dispor, em contrapartida, você também terá características conflitantes de perfis antagônicos,  nessa combinação, a dificuldade ocorre pela necessidade do D (Dominância) em realizar as atividades conflitar com a necessidade de avaliação e criação de um plano de ação gerada pelo S (Estabilidade) e muito bem analisado com as características de seu C (Conformidade), porém, havendo o equilíbrio entre ambos, ocorre o melhor de dois mundos, com a criação de um plano de ação ágil, a prova de falhas e com uma execução impecável.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "321": "A combinação de 3 perfis Dominantes é algo raro de acontecer, isso é uma coisa boa, pois você terá o melhor de cada mundo a seu dispor, em contrapartida, você também terá características conflitantes de perfis antagônicos, como é o caso do D (Dominância) e S (Estabilidade). Ao mesmo tempo em que o Dominante tende a realizar as atividades, o Estável tende a avaliar todos os caminhos possíveis. Sendo a maior dominância do Estável, a tendência é não sair fazendo, porém com a junção do perfil I (Influência) a impulsividade vem a tona e é preciso tomar cuidado para não se entediar ao criar um plano e sair executando sem avaliar adequadamente. A combinação desses perfis possibilita grandes conquistas, mas apenas se for tratada adequadamente, o que virá da clareza que você terá a partir de agora. \nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "324": "A combinação de 3 perfis Dominantes é algo raro de acontecer, isso é uma coisa boa, pois você terá o melhor de cada mundo a seu dispor, em contrapartida, você também terá características conflitantes de perfis antagônicos, na combinação desse perfil, S (Estabilidade) / I (Influência) / C (Conformidade) podem ocorrer \"faíscas\" internas ao precisar tomar algumas decisões, isso ocorre pois seu lado Conforme quer avaliar as informações possibilitando ao Estável traçar o melhor plano, porém o Influente se entedia com facilidade e não aceita ser deixado de lado, por isso o foco pode ser afetado para quem possui essa tríade.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "341": "A combinação de 3 perfis Dominantes é algo raro de acontecer, isso é uma coisa boa, pois você terá o melhor de cada mundo a seu dispor, em contrapartida, você também terá características conflitantes de perfis antagônicos, nessa combinação, existem 2 perfis que tendem a planejar e analisar as informações antes de agir, o C (Conforme) e o S (Estável), com a dominância do Estável é quase que certo que um excelente plano com as análises perfeitas será criado e após isso ocorrerá uma execução perfeita. Claro que existe o ponto de atenção gerado pelo conflito entre Estável e Dominante, mas é algo que pode ser trabalhado e com o apoio do Conforme a tendência é que o Dominante seja controlado, afinal ele pode entender que a análise de informações faz parte da execução de atividades.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "342": "A combinação de 3 perfis Dominantes é algo raro de acontecer, isso é uma coisa boa, pois você terá o melhor de cada mundo a seu dispor, em contrapartida, você também terá características conflitantes de perfis antagônicos, nessa tríade o I (Influência) pode ser abafado pelos perfis S (Estabilidade) e C (Conformidade), o que pode gerar certo desconforto pois esse lado seu pode se entediar com processos análises e coisas do tipo. A clareza das situações é peça chave para entender que não é ruim esperar para depois de tudo preparado usar sua excepcional capacidade de se comunicar para colocar a engrenagem para girar.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "412": "A combinação de 3 perfis Dominantes é algo raro de acontecer, isso é uma coisa boa, pois você terá o melhor de cada mundo a seu dispor, em contrapartida, você também terá características conflitantes de perfis antagônicos, no caso dessa combinação, o conflito ocorre entre perfis com uma boa comunicação e um alto grau de extroversão, D (Dominância) e I (Influência), com o perfil C (Conformidade) que é um perfil mais reservado. Com a clareza da situação, é possível aproveitar a sinergia, empolgação e iniciativa da combinação Dominância/Influência para aproveitar o que há de melhor na análise precisa gerada pelo alto C (Conformidade) das situações. Tentar anular seu lado Conforme pode gerar grande desconforto, por isso avalie o que pode realizar para saciar também seus lados Dominante e Influente.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "413": "A combinação de 3 perfis Dominantes é algo raro de acontecer, isso é uma coisa boa, pois você terá o melhor de cada mundo a seu dispor, em contrapartida, você também terá características conflitantes de perfis antagônicos,  nessa combinação, a dificuldade ocorre pela necessidade do D (Dominância) em realizar as atividades conflitar com a necessidade de avaliação e criação de um plano de ação gerada pelo S (Estabilidade) e muito bem analisado com as características de seu C (Conformidade), porém, havendo o equilíbrio entre ambos, ocorre o melhor de dois mundos, com a criação de um plano de ação ágil, a prova de falhas e com uma execução impecável.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "421": "A combinação de 3 perfis Dominantes é algo raro de acontecer, isso é uma coisa boa, pois você terá o melhor de cada mundo a seu dispor, em contrapartida, você também terá características conflitantes de perfis antagônicos, no caso dessa combinação, o conflito ocorre entre perfis com uma boa comunicação e um alto grau de extroversão, D (Dominância) e I (Influência), com o perfil C (Conformidade) que é um perfil mais reservado e que antes de tomar qualquer atitude avalia todos os pontos. Com a clareza da situação, é possível aproveitar a sinergia, empolgação e iniciativa da combinação Dominância/Influência para aproveitar o que há de melhor na análise precisa gerada pelo alto C (Conformidade) das situações.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "423": "A combinação de 3 perfis Dominantes é algo raro de acontecer, isso é uma coisa boa, pois você terá o melhor de cada mundo a seu dispor, em contrapartida, você também terá características conflitantes de perfis antagônicos, na combinação desse perfil,  C (Conformidade) / I (Influência) / S (Estabilidade) podem ocorrer \"faíscas\" internas ao precisar tomar algumas decisões, isso ocorre pois seu lado Conforme quer avaliar as informações possibilitando ao Estável traçar o melhor plano, porém um Influente dominante não aceita ser deixado de lado e se entedia fácil, por isso o foco pode ser afetado para quem possui essa tríade.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "431": "A combinação de 3 perfis Dominantes é algo raro de acontecer, isso é uma coisa boa, pois você terá o melhor de cada mundo a seu dispor, em contrapartida, você também terá características conflitantes de perfis antagônicos, nessa combinação, existem 2 perfis que tendem a planejar, analisar as informações antes de agir, o C (Conformidade) e o S (Estabilidade), com a dominância do Conforme é quase que certo que uma análise perfeita possibilitará a criação de um plano de ação Impecável e praticamente a prova de falhas, depois disso basta \"soltar\" o Dominante para realizar com perfeição o que foi planejado.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "432": "A combinação de 3 perfis Dominantes é algo raro de acontecer, isso é uma coisa boa, pois você terá o melhor de cada mundo a seu dispor, em contrapartida, você também terá características conflitantes de perfis antagônicos, nessa tríade o I (Influência) pode ser abafado pelos perfis S (Estabilidade) e C (Conformidade), o que pode gerar certo desconforto pois esse lado seu pode se entediar com processos análises e coisas do tipo. A clareza das situações é peça chave para entender que não é ruim esperar para depois de tudo preparado usar sua excepcional capacidade de se comunicar para colocar a engrenagem para girar.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "12": "A combinação de 2 perfis dominantes, não é algo raro de acontecer,essa combinação tende a ser muito boa, pois os dois perfis se completam. Entendendo as características de cada um você poderá conseguir o melhor de dois mundos.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "13": "A combinação de 2 perfis dominantes, não é algo raro de acontecer,na sua combinação podem ocorrer conflitos devido a características marcantes de cada perfil. Enquanto o D (Dominância) tende a resolver as coisas na hora, o S (Estabilidade) precisa criar um plano de ação assertivo. Essa diferença de características pode gerar certo desconforto em alguns momentos, porém com a clareza dessas características é possível tirar o melhor de cada um conseguindo excelentes resultados.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "14": "A combinação de 2 perfis dominantes, não é algo raro de acontecer,na sua combinação podem ocorrer conflitos devido a características marcantes de cada perfil. Enquanto o C (Conformidade) busca analisar todas as informações antes de tomar qualquer ação, o D (Dominância) tende a resolver as coisas na hora,  o que pode gerar certo desconforto em alguns momentos.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "21": "A combinação de 2 perfis dominantes, não é algo raro de acontecer,nessa combinação ocorre uma ótima combinação, pois os dois perfis se completam. Entendendo as características de cada um você poderá conseguir o melhor de dois mundos.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "23": "A combinação de 2 perfis dominantes, não é algo raro de acontecer,nessa combinação ocorre uma ótima combinação, pois os dois perfis se completam. Entendendo as características de cada um você poderá conseguir o melhor de dois mundos.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "24": "A combinação de 2 perfis dominantes, não é algo raro de acontecer,porém, essa combinação mostra dois perfis antagônicos I (Influência) e C (Conformidade). Enquanto um deles gosta de coisas agitadas e falta de rotina, o outro prefere ambientes calmos e processos bem desenhados. Ter esses dois perfis pode ser uma dádiva ou uma dor de cabeça, porém sabendo como cada um funciona, as vantagens e características de cada um, pode-se aprender a transitar entre cada um conquistando qualquer resultado necessário com maestria.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "31": "A combinação de 2 perfis dominantes, não é algo raro de acontecer,na sua combinação podem ocorrer conflitos devido a características marcantes de cada perfil. Enquanto o S (Estabilidade) precisa criar um plano de ação assertivo, o D (Dominância) tende a resolver as coisas na hora, muitas vezes de forma impulsiva . Essa diferença de características pode gerar certo desconforto em alguns momentos, porém com a clareza dessas características é possível tirar o melhor de cada um conseguindo excelentes resultados.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "32": "A combinação de 2 perfis dominantes, não é algo raro de acontecer,nessa combinação ocorre uma ótima combinação, pois os dois perfis se completam, pois ambos são perfis relacionais. Entendendo as características de cada um você poderá conseguir o melhor de dois mundos.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "34": "A combinação de 2 perfis dominantes, não é algo raro de acontecer,nessa combinação ocorre uma ótima combinação, pois os dois perfis se completam. Entendendo as características de cada um você poderá conseguir o melhor de dois mundos.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "41": "A combinação de 2 perfis dominantes, não é algo raro de acontecer,na sua combinação podem ocorrer conflitos devido a características marcantes de cada perfil. Enquanto o C (Conformidade) busca analisar todas as informações antes de tomar qualquer decisão, o D (Dominância) tende a resolver as coisas na hora, muitas veze agindo impulsivamente , o que pode gerar certo desconforto em alguns momentos.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "42": "A combinação de 2 perfis dominantes, não é algo raro de acontecer,porém, essa combinação mostra dois perfis antagônicos I (Influência) e C (Conformidade). Enquanto um deles gosta de coisas agitadas e falta de rotina, o outro prefere ambientes calmos e processos bem desenhados. Ter esses dois perfis pode ser uma dádiva ou uma dor de cabeça, porém sabendo como cada um funciona, as vantagens e características de cada um, pode-se aprender a transitar entre cada um conquistando qualquer resultado necessário com maestria.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "43": "A combinação de 2 perfis dominantes, não é algo raro de acontecer,nessa combinação ocorre uma ótima combinação, pois os dois perfis se completam. Entendendo as características de cada um você poderá conseguir o melhor de dois mundos.\nAbaixo segue maiores detalhes focados no seu maior perfil.",
  "1": "",
  "2": "",
  "3": "",
  "4": ""
};

export const DISC_SINGLE_PROFILES: Record<string, string> = {
  "D": "As pessoas com um perfil (D) dominante, tendem a ser ativos, competitivos, otimistas e dinâmicos. Gostam de desafios e assumem rapidamente a liderança em atividades, pois adoram assumir riscos. \nPela característica ágil e resolutiva, detestam processos lentos e falta de autonomia, isso gera um grande desgaste para um alto D (Dominância).\nSão autoconfiantes, determinados e autossuficientes e por isso podem se estressar com facilidade, vale prestar atenção ao controle emocional, já que podem ser irônicos, sarcásticos e as vezes arrogantes e tendem a fazer as coisas do jeito deles faltando com o respeito, se pressionados, por perderem o controle.",
  "I": "Pessoas com uma Influência alta (I), normalmente são extrovertidos, falantes, adaptáveis e ativos. Adoram falta de rotina, autonomia e trabalham muito bem em equipe, mas há um ponto de atenção nesse item, por serem comunicativos, tendem a perder o foco e se não acompanhados podem impactar negativamente no resultado de todo o time.\nPessoas desse perfil tem dificuldade com processos engessados, monotonia e falta de reconhecimento, em contrapartida, são afetuosos, carismáticos e conseguem envolver as pessoas em seus projetos mantendo o clima geral. Como ponto a desenvolver, podem ser impulsivos e exagerados, também buscam aprovação e atenção das outras pessoas e tendem a ser desorganizados. Outro ponto de atenção é que quando pressionados, podem se enrolar e prometer o que não conseguem entregar",
  "S": "Pessoas com S (Estabilidade) alto, tendem a ser calmos, prudentes e têm muito autocontrole. Adoram rotina, planejamento e ajudar os outras pessoas, sendo muito bons para a manutenção do clima da equipe. Já, a falta de disciplina e improvisações incomodam bastante, pois não gostam de surpresas, entendendo que por não terem avaliado as possibilidades algo pode dar errado. Na maioria das vezes são calmos, confiáveis, fácil de conviver, eficientes e extremamente organizados\nUm ponto de atenção é que tendem a ter uma autoestima baixa, podem ser indecisos por planejarem demais, impactando nos relacionamentos pessoais e profissionais, pois muitas vezes analisam a capacidade das outras pessoas a sua volta.\nQuando estão sob muita pressão, podem se calar por medo de magoar o outro, acumulando o sentimento dentro de si, dando a entender muitas vezes nessas situações que não gostam de se posicionar ou se expor.",
  "C": "O Perfil Conforme (C) é composto normalmente por pessoas detalhistas, precisos, cautelosos e críticos. Essas pessoas gostam de perfeição, métodos e ambientes calmos, mas não lidam bem com pressão, falta de garantias e falta de segurança. Tem altíssima capacidade analítica, são transparentes, disciplinados e sempre terminam o que começam, mas precisam desenvolver sua autoconfiança, pois tendem a ser pessimistas, autocríticos, e desgastam o relacionamento com outras pessoas apontando seus defeitos. \nEsse é um perfil que quando magoado não esquece com facilidade e revive a situação diversas vezes o que piora ainda mais a relação e sua autoconfiança e por isso acabam se calando e se tornam omissos dependendo da situação."
};

export const DISC_COMPETENCIES_DESC: Record<string, string> = {
  "Orientado por Resultados": "Pessoas com alta pontuação em nessa habilidade tendem a ser orientadas para resultados, e se concentram muito em alcançar metas e objetivos. Elas podem ser motivadas pela conquista e pelo sucesso, e gostam de tomar decisões rapidamente para manter o progresso em direção aos objetivos. Elas tendem a medir seu sucesso apenas pelo resultado obtido.",
  "Persuasão": "Pessoas com alta pontuação em Persuasão são extremamente influentes e convincentes, são ótimos em convencer os outros a adotar suas ideias ou seguir seu caminho, e baseiam sua argumentação em dados e fatos. Elas podem ser orientadas para vendas e negociações, e têm uma tendência a buscar a vitória em disputas, ficando frustradas quando não saem vitoriosas de uma negociação ou argumentação.",
  "Competitividade": "Pessoas altamente competitivas são motivadas pela superação de desafios. Elas gostam de estar no topo e podem ver a vida como uma competição constante, procurando sempre vencer e superar os outros. Quando este item é muito alto pode haver uma característica de vencer a qualquer custo.",
  "Energia": "Pessoas com alta pontuação nessa característica tendem a ser enérgicas e entusiasmadas, e muitas vezes são vistas como líderes naturais. Elas gostam de manter um ritmo acelerado e podem ser movidas pela adrenalina e pelos desafios. Em algumas situações dada a sua característica mais forte podem parecer arrogantes e que não ligam para o sentimento das pessoas a sua volta.",
  "Multitarefas": "Pessoas com essa habilidade tendem a ser eficientes em realizar muitas coisas ao mesmo tempo, sem perder o foco e a objetividade. Elas são boas em priorizar e gerenciar seu tempo, e podem ser motivadas pelo desejo de serem produtivas e eficientes, pois medem seu sucesso pela quantidade de entregas realizadas.",
  "Comunicação": "Pessoas com alta pontuação em comunicação tendem a ser excelentes comunicadores no geral, gostam de falar, contar histórias e se expressar de forma clara e envolvente. Elas têm uma habilidade natural para se comunicar com outras pessoas e para fazer conexões emocionais. São ótimos para lidar com público e tendem a ser a alma do meio em que vivem chamando toda a atenção para si em diversas situações.",
  "Flexibilidade": "Pessoas com alta pontuação nessa característica tendem a ser adaptáveis, resilientes e podem mudar de direção facilmente. Elas são abertas a novas ideias e experiências, e tendem a ser menos presas às regras e procedimentos. Lidam bem com mudanças bruscas e enxergam vantagem em situações imprevisíveis.",
  "Relacionamento Interpessoal": "Pessoas com alta pontuação em Influência tendem a ter habilidades sociais fortes, e são capazes de criar relacionamentos interpessoais positivos e duradouros. Elas têm uma habilidade natural para se conectar com outras pessoas, e tendem a ser extrovertidas e sociáveis. Valorizam muito essa relação e ficam chateados quando essa relação \"esfria\" sem saberem o motivo para tal.",
  "Criatividade": "Pessoas com alta pontuação nesse quesito tendem a ser imaginativas, e gostam de pensar fora da caixa. Elas têm uma capacidade natural para gerar ideias e soluções inovadoras, e podem ser motivadas pelo desejo de fazer algo novo e diferente. Ficam frustradas quando não podem buscar soluções e tendem a se entediar com facilidade caso fiquem \"amarrados\" a fluxos e processos engessados.",
  "Entusiasmo": "Pessoas com entusiasmo alto são animadas, e podem contagiar os outros com sua energia positiva. Elas têm uma habilidade natural para motivar e inspirar outras pessoas, e podem ser vistas como líderes informais. Chamam atenção em qualquer ambiente pela sua desenvoltura e animação constante.",
  "Empatia": "Pessoas com alta pontuação nessa característica tendem a ser preocupadas om o bem estar dos outros e têm uma capacidade natural de entender e se colocar no lugar das outras pessoas. Elas tendem a ser sensíveis as necessidades dos outros e podem ser ótimos ouvintes.",
  "Tolerância": "Pessoas com essa característica são respeitosas e tem uma incrível capacidade de aceitar e valorizar as diferenças dos outros. Elas tendem a ser menos críticas e evitam julgamentos, normalmente são vistas como pessoas gentis e amáveis, porém em algumas situações podem ser prejudicadas por outras pessoas que se aproveitam dessa qualidade.",
  "Capacidade de Trabalhar em Equipe": "Pessoas com alta pontuação nesse quesito tendem a ser excelentes para trabalhar com outras pessoas, valorizam e apreciam o trabalho em conjunto. Tendem a ser boas em construir relacionamentos interpessoais e podem ser excelentes mediadoras.",
  "Paciência": "Pessoas com essa característica alta tendem a ser tranquilas e podem tolerar situações difíceis e desafiadoras sem perder a calma. Tendem a ser menos propensas a reagir de forma exagerada ou impulsiva e podem ser excelentes para resolver situações de crise.",
  "Planejamento": "Pessoas com essa característica são planejadoras e motivadas por uma necessidade de ordem e estrutura. São ótimas em organizar projetos e tarefas de forma lógica e sistemática e são excelentes em funções que exigem precisão e atenção aos detalhes.",
  "Concentração": "Pessoas com essa característica alta são capazes de se concentrar em uma tarefa por longos períodos de tempo, e podem ser bastante persistentes na busca de um objetivo. Elas tendem a ser menos distraídas e mais orientadas para tarefas do que para pessoas.",
  "Atenção aos Detalhes": "Pessoas com alta pontuação nesse quesito tendem a ser altamente precisas e minuciosas em sua abordagem ao trabalho, e são capazes de identificar e corrigir erros e inconsistências. Elas tendem a ser menos propensas a cometer erros ou omissões em seu trabalho e são extremamente perfeccionistas.",
  "Rigorosidade": "Pessoas com alta pontuação nesse quesito tendem a ser rigorosas e exigentes consigo mesmas e com os outros, e têm uma alta tolerância à frustração e ao trabalho repetitivo. Elas tendem a ser motivadas por padrões elevados de qualidade e excelência. Devido a serem muito rigorosos podem ter problemas de relacionamento com outras pessoas.",
  "Análise": "Pessoas com essa característica tendem a ser analíticas e lógicas em sua abordagem ao trabalho, e são capazes de identificar padrões e tendências em dados e informações. Elas tendem a ser menos propensas a tomar decisões com base em emoções ou intuição, inclusive no que tange sua vida pessoal.",
  "Consistência": "Pessoas com alta Consistência tendem a ser confiáveis em sua abordagem ao trabalho, e são capazes de manter padrões elevados de desempenho ao longo do tempo. Elas tendem a ser menos propensas a flutuações de humor ou de motivação."
};

export const DISC_PROFILE_DETAILS: Record<string, {
  keywords: string[];
  strengths: string[];
  develop: string[];
  pressure: string[];
}> = {
  D: {
    keywords: ["Resultado", "Diretos", "Decisivos"],
    strengths: ["Autoconfiantes", "Decididos", "Otimistas", "Empreendedores", "Competitivos", "Gostam de liderar"],
    develop: ["Se estressam com facilidade", "Indiferentes", "Intensos", "Orgulhosos", "Dominadores"],
    pressure: ["Arrogantes"]
  },
  I: {
    keywords: ["Entusiasmo", "Diversão", "Imagem"],
    strengths: ["Persuasivos", "Sociáveis", "Carismáticos", "Gostam de mudanças", "Não guardam rancor", "Se preocupam com as pessoas"],
    develop: ["Agitados", "Exagerados", "Impulsivos", "Buscam aprovação", "Desorganizados"],
    pressure: ["Perda de foco frequente"]
  },
  S: {
    keywords: ["Estabilidade", "Paciência", "Processos"],
    strengths: ["Calmos", "Alegres", "Confiáveis", "Consistentes", "Conservadores", "Prezam pela qualidade"],
    develop: ["Autoestima baixa", "Pessimistas", "Teimosos", "Extremamente preocupados", "Indecisos"],
    pressure: ["Não gostam de mudanças"]
  },
  C: {
    keywords: ["Exatidão", "Corretos", "Cuidadosos"],
    strengths: ["Alta capacidade analítica", "Perfeccionistas", "Sinceros", "Transparentes", "Inteligentes", "Cautelosos"],
    develop: ["Pessimistas", "Autocríticos", "Orgulhosos", "Guardam mágoa", "Demoram para entregar tarefas"],
    pressure: ["Tendem a ser críticos com os outros"]
  }
};
